default:
  tags:
    - CREMI 
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

buid-job1:
  stage: build
  script :
    - pip install coverage

test-job1:
  stage: test
  script :
    - python3 -m unittest -v test/tests.py